### PR TITLE
Add 2.11 TAS support

### PR DESCRIPTION
**Pull request by kirederik**
> Which other branches should this be merged with (if any)?

None

### CODE REVIEW

**Comment by jncd** [comment]
@kirederik 
Thanks for doing the PR!

**Comment by jncd** [comment]
@kirederik What should I do with the Windows version? 
Should I just add 2.11 to the TAS for Windows line too? 
Screen Shot 2021-05-18 at 5 30 20 PM

  (For other addons, we don't list Windows separately. But it mattered in FIM v1.4, and so it stuck.)

**Comment by kirederik** [comment]
Hey @jncd,

Yes, that's right -- it should be compatible with Windows as well. I missed the extra line 😅

**Comment by jncd** [comment]
Thanks @kirederik 

I'm marking my [story](https://www.pivotaltracker.com/story/show/178201198) about snapshot updates for 2.11 as done!

**Pull request merged**
