### PR TITLE
[#175942192] update container paths

### PR DESCRIPTION
**Pull request by xtreme-nitin-ravindran**
Which other branches should this be merged with (if any)?

All supported branches

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @xtreme-nitin-ravindran 
I'll merge, cherry-pick and publish.

**Comment by jncd** [comment]
@xtreme-nitin-ravindran I'm going to change the other two instances of "images" on this page as well: 

Screen Shot 2020-12-01 at 4 40 53 PM

**Comment by xtreme-nitin-ravindran** [comment]
@jncd Can you cherry-pick the commit on 2.0 branch? The support folks want it there since its till up. https://pivotal-io.atlassian.net/browse/PLATSEC-12

**Comment by Pivotal-Christopher-Wong** [comment]
@jncd I already made the changes to 2.0, so disregard the above!

**Comment by jncd** [comment]
And another one: I'll fix and cherry-pick back to 2.0.
Screen Shot 2020-12-03 at 12 22 12

**Pull request merged**
